### ISSUE TITLE
encodeNodes(nodes) error

### ISSUE THREAD

**Issue by laino** [drxzcl/lightdht#1]
In some conditions encodeNodes(nodes) would get called with Node-objects and tuples, resulting in an error.
I forked your repo and implemented a fix. You might want to change all the tabs back to spaces before pushing my fix to your repo (if you want to use it), the diff will not have any usable output otherwise.

There's some more info in my comment here:
https://github.com/binlain/lightdht/commit/622d66e85ed965bf9efb9d30be2f48935032b06d#commitcomment-1903113

I also want to use this comment to tell you how much I appreciate your work because you probably saved me weeks of writing this myself: 

Thank You.

**Comment by drxzcl** [comment]
Thanks for the report. I'm glad the code it helped you out in a small way. In the old days it would just be taking up space on my drive, but now people can actually use it!

I have fixed this issue in my own (offline) repository, but I have not pushed to GitHub because it's become a bit entangled in my application code and I have not had either the time or the inclination to disentangle it. I actually might do that though now that I think about it, since it does adds proper peer management and announce capabilities.

**Comment by drxzcl** [comment]
I finally got around to merging your changes. Thanks bunches!
